language: java
before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer show -i
script: ant build.all.artifacts
deploy:
  provider: releases
  file: "artifacts.zip"
  skip_cleanup: true
  on:
    tags: true
